server:
    port: 9999
    servlet:
        context-path: /auth



spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/lemmeknow-security
        username: postgres
        password: Yfevtyrj1
        driver-class-name: org.postgresql.Driver
        initialization-mode: always
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        generate-ddl: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL92Dialect
                show_sql: true
                format_sql: true

logging:
    level:
        org.springframework.security: DEBUG
        org.springframework.web: DEBUG